#!/usr/bin/env bash

local c_status="$?"

local git
git="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"

local venv
venv="${VIRTUAL_ENV##*/}"

local dir='\W'
local propt_char="${COFFEE_ROOT_CHAR:-#}"
local user_colour="${COFFEE_CLR_USER:-${COFFEE_PROMPT_GREEN}}"

[ $UID != '0' ] && local propt_char="${COFFEE_USER_CHAR:-%}"
[ $c_status != '0' ] && local propt_colour="${COFFEE_CLR_ERR:-${COFFEE_PROMPT_RED}}$c_status "
[ "$git" ] && local dir="($git) $dir"
[ "$venv" ] && local extra="{${COFFEE_CLR_VENV:-${COFFEE_PROMPT_GREEN}}$venv${COFFEE_PROMPT_RESTORE}} "
[ $UID == '0' ] && local user_colour="${COFFEE_CLR_ROOT:-${COFFEE_PROMPT_RED}}"

export PS1="\n${extra}${user_colour}\u${COFFEE_PROMPT_RESTORE}@\h ${dir} ${propt_colour}${propt_char}${COFFEE_PROMPT_RESTORE} "
